services:
  redis:
    image: redis:latest
    container_name: redis_container
    command:
      - 'redis-server'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
    networks:
      - bot_network
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - .env
    networks:
      - bot_network
    depends_on:
      - redis


networks:
  bot_network:
    driver: bridge
