services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - .env
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
